### ISSUE TITLE
Noetic release for Ubuntu Focal

### ISSUE THREAD

**Issue by davefeilseifer** [Slamtec/rplidar_ros#44] opened 2021-03-07 08:04 UTC
rplidar_ros passes prerelease testing:

generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  noetic default ubuntu focal amd64 \
  --custom-repo \
    rplidar__custom-1:git:https://github.com/Slamtec/rplidar_ros.git:master \
  --level 0 \
  --output-dir ./

ready for release into focal/noetic

**Comment by dimaqq** [comment] 2022-01-24 07:19
poke!

**Comment by Timple** [comment] 2022-01-24 11:32
Duplicate of #40 I think :slightly_smiling_face:

**Comment by deyouslamtec** [comment] 2023-05-12 08:20
Duplicate of #40

**Closed by deyouslamtec** 2023-05-12 08:20 UTC
